name: Deploy
on:
  push:
    branches:
      - 'main'

jobs:
  deploy-next:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Next.JS Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blog-rodjosh"
          heroku_email: "joshua.david.rodriguez.medrano@gmail.com"
          appdir: client

  deploy-strapi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Strapi Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blog-strapi-rodjosh"
          heroku_email: "joshua.david.rodriguez.medrano@gmail.com"
          appdir: server