name: Lint project
on: [push]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with:
        node-version: '14'
    - name: Run frontend linting
      working-directory: ./client
      run: ls && cd client && npm install && npm run lint
