name: 'Storybook'

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '14'
      - name: Running chromatic cli
        working-directory: ./client
        env:
          TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          npm install
          npm install -g yarn
          yarn chromatic --project-token "$TOKEN"