name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '14'
      - name: Test Next.JS Files
        working-directory: ./client
        run: |
          npm install
          npm install -g yarn
          yarn test
